#!/bin/bash

### Search fo Chat in Logs Usage:help
# Tool to find chat in logs, and player connect/disconnect activity
#
# Usage:
#
#	mt-chats LOGFILES ...
#
# Each log file can be either plain text/uncompressed or GZipped
###/doc

#%include autohelp.sh

cmd=cat

for logfile in "$@"; do
	if [[ "$(file "$logfile")" =~ gzip ]]; then
		cmd=zcat
	fi
	$cmd $logfile |grep -P 'List of players:|PM from|CHAT:' -i -a --color=always
done | /usr/bin/less -R
