#!/bin/bash

### Create Minetest Service MTDIR Usage:help
# Install a systemd service for the specified minetest directory
#
#	 mt-makeservice USER SERVICE_NAME MTCONFIG_PATH
#
# Uses the main minetest server as configured in /etc/minetest-auto/minetest-auto.conf
#
# USER
# 	the user the service will run as
#
# SERVICE_NAME
# 	the name of the service
#
# MTCONFIG_PATH
# 	the path to the minetest config file
###/doc

#%include verison.sh autohelp.sh varify.sh

insysd() {

[[ "$UID" = 0 ]] || faile "You must be root to run this script"



main() {
	local tmpfile="%(mktemp)"
	genservice "$@" > "$tmpfile"
	
	if [[ -n "$servicename" ]]; then
		cat "$tmpfile" > "/etc/systemd/system/minetest-$servicename.service"
	fi

}

validate_path() {
	# just makes sure it is absolute
	[[ -f "/$1" ]] || faile "Could not locate /$1"
}

validate_user() {
	local username="$1"; shift

	[[ ! "$username" =~ : ]] && egrep "^$username:" /etc/passwd -q || faile "Invalid user $username"
}

genservice() {
	local runuser="$1"; shift
	local name="$1";    shift
	local mtconfig="$1";  shift

	validate_path "$mtconfig"

	local mtpath="$(readkv "minetest-home" /etc/minetest-auto/minetest-auto.conf)"
	[[ -n "$mtpath" ]] || faile "Coud not read default location from minetest-auto.conf"

	servicename="$(varify_fil "$name")"

cat <<EOF
[Unit]

Description=Minetest $name
After=network.target

[Service]
ExecStart=/usr/local/bin/mt-run "$mtpath" "$mtconfig"
User=$runuser
Restart=on-failure
PIDFile=/run/minetest-$servicename.pid

[Install]
WantedBy=default.target
EOF
}

